export const endPointApi = {
  LOGIN: "auth/v1/login",
  RESGITER: "auth/v1/resgiter",
  API_TOKEN: "auth/v1/token",
  LOGOUT: "auth/v1/logout",
  CATEGORIES: "category/v1",
  TYPE_COURSES: "type-course/v1",
  USERS: "user/v1",
  COURSES: "course/v1",
  UPLOAD_IMAGE: "upload/v1/image",
  DISCOUNTS: "discount/v1",
  TOPICS: "topic/v1",
  LESSONS: "lesson/v1",
  USERS_COURSE: "user-course/v1",
  PAYOS: "payos/v1",
};
